# Generated by Django 3.2.4 on 2021-07-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, verbose_name='Package')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Journals_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Journal name')),
                ('URL', models.URLField(blank=True, null=True)),
                ('P_ISSN', models.CharField(blank=True, max_length=100, null=True)),
                ('E_ISSN', models.CharField(blank=True, max_length=100, null=True)),
                ('Package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='journals.package')),
                ('Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='journals.subject')),
            ],
            options={
                'ordering': ('Title',),
            },
        ),
    ]
